name: Cypress Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies cleanly
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Generate Excel report
        if: always()
        run: npm run Run_and_update_Result_sheet

      - name: Generate combined Mochawesome report (JSON + HTML)
        if: always()
        run: |
          npm run getMochawesomeReport
          npm run getHTMLReport

      - name: Install jq for JSON parsing
        if: always()
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract test summary stats from output.json
        if: always()
        id: extract_results
        run: |
          if [ -f output.json ]; then
            total_passed=$(jq '.stats.passes' output.json)
            total_failed=$(jq '.stats.failures' output.json)
            total_pending=$(jq '.stats.pending' output.json)
            failed_cases=$(jq -r '[.results[] | .suites[].tests[] | select(.state == "failed") | .title] | join(", ")' output.json)
            total_tests=$((total_passed + total_failed + total_pending))

            echo "TOTAL_TESTS=$total_tests" >> $GITHUB_ENV
            echo "TOTAL_PASSED=$total_passed" >> $GITHUB_ENV
            echo "TOTAL_FAILED=$total_failed" >> $GITHUB_ENV
            echo "TOTAL_PENDING=$total_pending" >> $GITHUB_ENV
            echo "FAILED_CASES=$failed_cases" >> $GITHUB_ENV
          else
            echo "output.json not found, skipping stats extraction."
          fi

      - name: Send test results via email with attachments
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: siddhantsourceandcode@gmail.com
          password: jfgt antr xuzj dish
          to: vaibhavps0595@gmail.com, siddhantgadakh121@gmail.com
          from: siddhantsourceandcode@gmail.com
          subject: "Cypress Test Results - Run #${{ github.run_number }} on $(date +'%d-%m-%Y')"
          attachments: |
            output.json
            mochawesome-report/output.html
            Daily_Tracker.xlsx
          body: |
            Dear Team,

            Here are the Cypress test results from the latest run:
            - Total Testcases: ${{ env.TOTAL_TESTS }}
            - Passed: ${{ env.TOTAL_PASSED }}
            - Failed: ${{ env.TOTAL_FAILED }}
            - Pending: ${{ env.TOTAL_PENDING }}
            - Failed Test Cases: ${{ env.FAILED_CASES }}

            Please find the attached reports.

            Regards,
            Automation Team
