name: Cypress Tests

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (UTC +5:30)
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install all dependencies from package.json
        run: npm install

      - name: Run Cypress tests with mochawesome reporter
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=true,html=false,json=true

      - name: Generate combined mochawesome report
        if: always()
        run: |
          npx mochawesome-merge cypress/results/*.json -o output.json
          npx marge output.json --reportDir mochawesome-report --inline

      - name: Generate Excel report
        if: always()
        run: node runAllSteps.js

      - name: Upload artifacts (JSON, HTML, Excel)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            output.json
            mochawesome-report/*.html
            test_results.xlsx

      - name: Install jq
        if: always()
        run: sudo apt-get install -y jq

      - name: Extract test result summary
        if: always()
        id: extract_results
        run: |
          total_passed=$(jq '.stats.passes' output.json)
          total_failed=$(jq '.stats.failures' output.json)
          total_pending=$(jq '.stats.pending' output.json)
          failed_cases=$(jq -r '[.results[] | .suites[].tests[] | select(.state == "failed") | .title] | join(", ")' output.json)

          total_tests=$((total_passed + total_failed + total_pending))

          echo "TOTAL_TESTS=$total_tests" >> $GITHUB_ENV
          echo "TOTAL_PASSED=$total_passed" >> $GITHUB_ENV
          echo "TOTAL_FAILED=$total_failed" >> $GITHUB_ENV
          echo "TOTAL_PENDING=$total_pending" >> $GITHUB_ENV
          echo "FAILED_CASES=$failed_cases" >> $GITHUB_ENV

      - name: Send test results via email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          to: vaibhavps0595@gmail.com, siddhantgadakh121@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: "Cypress Test Results - $(date +'%d-%m-%y')"
          attachments: |
            output.json
            mochawesome-report/*.html
            test_results.xlsx
          body: |
            Dear Team,

            Here are the Cypress test results from the latest run:
            - Total Run Testcases: ${{ env.TOTAL_TESTS }}
            - Total Passed: ${{ env.TOTAL_PASSED }}
            - Total Failed: ${{ env.TOTAL_FAILED }}
            - Total Pending: ${{ env.TOTAL_PENDING }}
            - Failed Test Cases: ${{ env.FAILED_CASES }}

            Please check the attached report and Excel file for detailed information.

            Best regards,
            Your Automation Team
